import { logger } from '../utils/logger.js';
import { EmbedBuilder } from 'discord.js';

/**
 * Publishes a game news message to the configured Discord channel.
 * @param {Client} client - Discord.js client instance
 * @param {Object} payload - Game news payload
 * @param {string} payload.game - Game title (required)
 * @param {string} payload.title - News title (required)
 * @param {string} payload.message - News message (required)
 * @param {string} [payload.url] - Optional URL to include
 * @param {Object} [payload.embed] - Optional embed configuration from the Game News Backend
 * @returns {Promise<{success: boolean, error?: string}>}
 */
export async function publishGameNews(client, payload) {
  try {
    const gameNewsChannelId = process.env.GAME_NEWS_CHANNEL_ID;

    if (!gameNewsChannelId) {
      logger.error('GAME_NEWS_CHANNEL_ID is not configured');
      return { success: false, error: 'Channel not configured' };
    }

    const game = String(payload.game ?? '').trim();
    const title = String(payload.title ?? '').trim();
    const message = String(payload.message ?? '').trim();
    const url = String(payload.url ?? '').trim();

    if (!game || !title || !message) {
      return {
        success: false,
        error: 'game, title and message are required',
      };
    }

    // Use the embed generated by the central Game News Backend.
    const embedData =
      payload.embed && typeof payload.embed === 'object'
        ? payload.embed
        : {
            title,
            description: message,
            color: 0x5865f2,
            footer: {
              text: `${game} • Game News`,
            },
            timestamp: new Date().toISOString(),
          };

    const embed = new EmbedBuilder();

    if (embedData.title) {
      embed.setTitle(String(embedData.title));
    }

    if (embedData.description) {
      embed.setDescription(String(embedData.description));
    }

    if (embedData.color !== undefined) {
      embed.setColor(Number(embedData.color));
    }

    if (embedData.url) {
      embed.setURL(String(embedData.url));
    } else if (url) {
      embed.setURL(url);
    }

    if (embedData.footer?.text) {
      embed.setFooter({
        text: String(embedData.footer.text),
      });
    }

    if (embedData.timestamp) {
      embed.setTimestamp(new Date(embedData.timestamp));
    }

    const channel = await client.channels.fetch(gameNewsChannelId);

    if (!channel || typeof channel.send !== 'function') {
      logger.error(
        'Game news channel could not be fetched or is not a text channel',
      );

      return { success: false, error: 'Channel error' };
    }

    await channel.send({
      embeds: [embed],
    });

    logger.info(
      `Game news published: ${game} - ${title}`,
    );

    return { success: true };
  } catch (error) {
    logger.error('Game news error:', error);
    return { success: false, error: 'Failed to publish' };
  }
}
